Repository MODU-TAXI/ios, pull requests merged in 2024-03, with the labels that each got.

#5 MTIOS-5 nativewind 설치 및 세팅
  babel.config.js
  ios/Podfile.lock
  package-lock.json
  package.json
  tailwind.config.js
  yarn.lock
Labels: SETTING

#6 MTIOS-3 setting eslint/prettier
  .eslintrc.js
  .prettierrc.js
  App.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  yarn.lock
Labels: SETTING

#7 MTIOS-4 setting folder structure
  src/api/apiInstance.ts
  src/assets/asset.ts
  src/assets/fonts/font
  src/assets/images/image
  src/components/component.ts
  src/config/config.ts
  src/hooks/hook.ts
  src/screens/screen.ts
Labels: SETTING

#8 MTIOS-5 App.tsx nativewind 변환 작업에 lint 적용
  App.tsx
  babel.config.js
  global.d.ts
Labels: FIX

#16 Mi 27 feature signup screen
  AppInner.tsx
  babel.config.js
  ios/Podfile.lock
  metro.config.js
  package-lock.json
  package.json
  src/assets/images/image
  src/assets/images/signIn/SignIn/bell.svg
  src/assets/images/signIn/SignIn/camera.svg
  src/assets/images/signIn/SignIn/location.svg
  src/assets/images/signIn/SignIn/tray.svg
  src/components/Button.tsx
  src/components/InputBox.tsx
  src/components/component.ts
  src/screens/Landing.tsx
  src/screens/SignIn/SignIn.tsx
  src/screens/signUp/AuthenticationCode.tsx
  src/screens/signUp/CheckPermission.tsx
  src/screens/signUp/CompleteSignUp.tsx
  src/screens/signUp/NicknameValidation.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/types/ParamLists.ts
  src/types/custom-library-types/declarations.d.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: FEATURE

#22 Mi 59 feature map screen
  AppInner.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/images/RoomDigest/ArrowRight.svg
  src/assets/images/RoomDigest/ChevronDown.svg
  src/assets/images/RoomDigest/ClockFill.svg
  src/assets/images/RoomDigest/LocationFill.svg
  src/assets/images/RoomDigest/MagnifyingGlass.svg
  src/assets/images/RoomDigest/Person2Fill.svg
  src/assets/images/RoomDigest/XmarkCircleFill.svg
  src/components/RoomDigest/FilterButton.tsx
  src/components/RoomDigest/RoomDigestBox.tsx
  src/components/RoomDigest/RoomTag.tsx
  src/components/RoomDigest/SearchLocationButton.tsx
  src/screens/map/MainMap.tsx
  src/screens/map/MapBottomSheet.tsx
  src/type/ParamLists.ts
  yarn.lock
Labels: FEATURE

#24 MI-61 setting tailwind.config.js
  tailwind.config.js
Labels: SETTING
