Repository MODU-TAXI/ios, pull requests merged in 2024-07, with the labels that each got.

#92 Mi 319 fix etc
  AppInner.tsx
  ios/modutaxi.xcodeproj/project.pbxproj
  src/components/Home/HomeHeader.tsx
  src/components/Home/InputBox.tsx
  src/components/Home/Parties.tsx
  src/components/Home/UserSummary.tsx
  src/components/Match/Category.tsx
  src/components/RoomDigest/SelectedRoomDigest.tsx
  src/components/Search/ArrivalSearchBox.tsx
  src/components/Search/DepartureSearchBox.tsx
  src/components/Search/RecommendedSearch.tsx
  src/components/Search/SpotSelectionSearch.tsx
  src/hooks/api/member.ts
  src/hooks/api/search.ts
  src/hooks/api/spot.ts
  src/hooks/permission/checkLocation.ts
  src/hooks/permission/checkPermissions.ts
  src/hooks/permission/location.ts
  src/screens/home/Home.tsx
  src/screens/map/ArrivalMap.tsx
  src/screens/map/DepartureMap.tsx
  src/screens/map/MainMap.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/search/ArrivalSearch.tsx
  src/screens/search/DepartureSearch.tsx
  src/screens/search/HomeSearch.tsx
  src/screens/search/MainMapSearch.tsx
  src/screens/withdraw/WithdrawLast.tsx
  src/server/api/member.ts
  src/server/api/spot.ts
  src/server/errorHandler/mutateErrorHandler.ts
  src/server/requestTypes/spot.ts
  src/server/responseTypes/member.ts
  src/type/param/loginStack.ts
  src/utils/map.ts
Labels: FIX

#94 Mi 353 fix qa
  src/components/Header.tsx
  src/hooks/api/member.ts
  src/hooks/api/rooms.ts
  src/screens/home/Home.tsx
  src/screens/map/DepartureMap.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/search/HomeSearch.tsx
  src/server/api/member.ts
  src/type/param/loginStack.ts
Labels: FIX

#96 Mi 381 refactor etc
  android/app/src/main/assets/fonts/Pretendard-Black.otf
  android/app/src/main/assets/fonts/Pretendard-Bold.otf
  android/app/src/main/assets/fonts/Pretendard-ExtraBold.otf
  android/app/src/main/assets/fonts/Pretendard-ExtraLight.otf
  android/app/src/main/assets/fonts/Pretendard-Light.otf
  android/app/src/main/assets/fonts/Pretendard-Medium.otf
  android/app/src/main/assets/fonts/Pretendard-Regular.otf
  android/app/src/main/assets/fonts/Pretendard-SemiBold.otf
  android/app/src/main/assets/fonts/Pretendard-Thin.otf
  android/link-assets-manifest.json
  ios/link-assets-manifest.json
  ios/modutaxi.xcodeproj/project.pbxproj
  react-native.config.js
  src/assets/fonts/Pretendard-Black.otf
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard-Thin.otf
  src/assets/fonts/font
  src/components/DatePicker.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/InputBox.tsx
  src/components/Marker/PressMarker.tsx
  src/components/Modal/DropDownModal.tsx
  src/components/Modal/MapBottomSheet.tsx
  src/components/RadioBox.tsx
  src/components/RoomDigest/RoomDigestBox.tsx
  src/components/RoomDigest/SelectedRoomDigest.tsx
  src/components/RoomDigest/WaitingUser.tsx
  src/components/Search/ArrivalSearchBox.tsx
  src/components/Search/DepartureSearchBox.tsx
  src/components/Search/LatestSearch.tsx
  src/components/Search/SearchBox.tsx
  src/components/Search/SpotSearch.tsx
  src/components/Search/SpotSelectionSearch.tsx
  src/components/Search/TransparentSearchBox.tsx
  src/components/SelectBox.tsx
  src/hooks/device.ts
  src/screens/main/Main.tsx
  src/screens/map/MainMap.tsx
  src/screens/search/ArrivalSearch.tsx
  src/screens/withdraw/WithdrawCheck.tsx
  src/screens/withdraw/WithdrawComplete.tsx
  src/screens/withdraw/WithdrawLast.tsx
  src/screens/withdraw/WithdrawSurvey.tsx
Labels: REFACTOR

#98 Refactor 0713
  src/assets/images/Chat/SchoolBadge.svg
  src/assets/images/Home/Map.svg
  src/assets/images/Home/MapPng.png
  src/assets/images/Home/Road.svg
  src/assets/images/Home/RoadPng.png
  src/components/Common/UserModal.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/HomeMainPanel.tsx
  src/components/Home/UserSummary.tsx
  src/hooks/api/member.ts
  src/screens/home/Home.tsx
  src/server/api/member.ts
  src/server/responseTypes/member.ts
  src/type/entity/user.ts
Labels: REFACTOR

#100 Refactor 0714
  AppInner.tsx
  src/components/Modal/MapBottomSheet.tsx
  src/components/Search/ArrivalSearchBox.tsx
  src/components/Search/DepartureSearchBox.tsx
  src/components/Search/SearchBox.tsx
  src/screens/NaverMap.tsx
  src/screens/map/MainMap.tsx
  src/screens/my/PatchUserInfo.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/search/ArrivalSearch.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/screens/test.tsx
  src/screens/withdraw/WithdrawComplete.tsx
  src/screens/withdraw/WithdrawLast.tsx
  src/server/api/chat.ts
  src/server/api/payment.ts
  src/server/api/spot.ts
  src/type/param/loginStack.ts
  src/utils/map.ts
  src/utils/search.ts
Labels: REFACTOR

#102 Mi 384 final refactor
  AppInner.tsx
  src/assets/images/Calculate/Arrow.svg
  src/assets/images/Calculate/CopyButton.svg
  src/assets/images/Calculate/Pencil.svg
  src/assets/images/Calculate/RefreshButton.svg
  src/assets/images/Calculate/TossPay.svg
  src/assets/images/Home/Bell.svg
  src/assets/images/RadioBox/SelectedRadioButton.svg
  src/assets/images/RadioBox/SelectedRadioButtonGray.svg
  src/components/Calculate/InputBox.tsx
  src/components/Calculate/MyAccount.tsx
  src/components/Calculate/ParticipateMember.tsx
  src/components/Calculate/PaymentMember.tsx
  src/components/Calculate/UnParticipateMember.tsx
  src/components/Chat/LastMessageComponent.tsx
  src/components/Chat/Messages.tsx
  src/components/DatePicker.tsx
  src/components/History/HistoryMember.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/NoParty.tsx
  src/components/Home/Parties.tsx
  src/components/Home/Party.tsx
  src/components/Home/UserSummary.tsx
  src/components/Modal/MapBottomSheet.tsx
  src/components/RoomDigest/RoomHeader.tsx
  src/components/RoomDigest/WaitingUser.tsx
  src/components/RoomDigest/WaitingUsers.tsx
  src/hooks/api/rooms.ts
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/calculate/Account.tsx
  src/screens/calculate/Amount.tsx
  src/screens/calculate/CheckAccount.tsx
  src/screens/calculate/CheckCalculate.tsx
  src/screens/calculate/CheckPayment.tsx
  src/screens/calculate/SendMoney.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/home/Home.tsx
  src/screens/map/MainMap.tsx
  src/screens/my/PatchSchoolEmailAuthentication.tsx
  src/screens/my/PatchUserInfoAuthentication.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/server/api/payment.ts
  src/server/requestTypes/account.ts
  src/server/responseTypes/payment.ts
  src/type/entity/user.ts
  src/type/param/loginStack.ts
  src/utils/pay.ts
  src/utils/toastMessage.ts
Labels: FEATURE, FIX, REFACTOR

#103 hotfix
  ios/modutaxi.xcodeproj/project.pbxproj
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
Labels: FIX

#105 Mi 401 0728
  ios/modutaxi.xcodeproj/project.pbxproj
  src/assets/images/Chat/ModutaxiBotChatImage.svg
  src/assets/images/Chat/ProfileImage.svg
  src/assets/images/Common/ModutaxiBotImage.svg
  src/components/Alarm/alarm.tsx
  src/components/Chat/CallTaxiMessageBox.tsx
  src/components/Chat/ChatBotMessageBox.tsx
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/LastMessageComponent.tsx
  src/components/Chat/MatchCompleteMessageBox.tsx
  src/components/Chat/Messages.tsx
  src/components/Chat/MyImageMessageBox.tsx
  src/components/Chat/OthersImageMessageBox.tsx
  src/components/Chat/PaymentMessageBox.tsx
  src/components/Chat/PaymentRequestMessageBox.tsx
  src/components/Common/SelectImageModal.tsx
  src/components/Common/UserModal.tsx
  src/components/Home/UserSummary.tsx
  src/components/Match/Category.tsx
  src/config/toastConfig.tsx
  src/hooks/api/account.ts
  src/hooks/api/member.ts
  src/hooks/api/rooms.ts
  src/screens/calculate/Account.tsx
  src/screens/calculate/Amount.tsx
  src/screens/calculate/CheckAccount.tsx
  src/screens/calculate/CheckCalculate.tsx
  src/screens/calculate/CheckPayment.tsx
  src/screens/calculate/CompeleteCalculate.tsx
  src/screens/calculate/SendMoney.tsx
  src/screens/calculate/checkDeparture.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/declaration/Declaration.tsx
  src/screens/history/HistoryDetail.tsx
  src/screens/my/MyPage.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/CheckPermission.tsx
  src/screens/signUp/CompleteSignUp.tsx
  src/screens/signUp/EmailAuthenticationCode.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/screens/signUp/RegisterNickname.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/screens/signUp/SurveyFirst.tsx
  src/screens/signUp/SurveySecond.tsx
  src/screens/withdraw/WithdrawCheck.tsx
  src/screens/withdraw/WithdrawComplete.tsx
  src/screens/withdraw/WithdrawLast.tsx
  src/screens/withdraw/WithdrawSurvey.tsx
  src/server/api/member.ts
  src/server/errorHandler/mutateErrorHandler.ts
  src/utils/fcm.ts
  src/utils/image.ts
  src/utils/pay.ts
  src/utils/toastMessage.ts
Labels: FEATURE, FIX, REFACTOR
