Repository MODU-TAXI/ios, pull requests merged in 2024-04, with the labels that each got.

#29 MI-67 add borderColor to buttom component
  src/assets/images/SignIn/AppleLogo.svg
  src/assets/images/SignIn/KakaoLogo.svg
  src/assets/images/SignUp/ReSendCodeButton.svg
  src/assets/images/SignUp/bell.svg
  src/assets/images/SignUp/camera.svg
  src/assets/images/SignUp/location.svg
  src/assets/images/SignUp/tray.svg
  src/components/Button.tsx
  src/screens/SignIn/SignIn.tsx
  src/screens/match/CreateMatch.tsx
  src/screens/match/Match.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/CheckPermission.tsx
  src/screens/signUp/CompleteSignUp.tsx
  src/screens/signUp/EmailAuthenticationCode.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/screens/signUp/SurveyFirst.tsx
  src/screens/signUp/SurveySecond.tsx
Labels: FIX

#30 MI-69 add timer in Input component
  src/components/InputBox.tsx
  src/components/Timer.tsx
  src/screens/signUp/EmailAuthenticationCode.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
Labels: FEATURE

#32 MI-68 connect kakao login
  babel.config.js
  src/api/api.ts
  src/axios/axios.Instance.ts
  src/axios/axios.method.ts
  src/components/Button.tsx
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/SignIn/SignIn.tsx
  src/screens/match/CreateMatch.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/screens/signUp/SurveyFirst.tsx
  src/screens/signUp/SurveySecond.tsx
  src/server/api/member.ts
  src/server/custom.error.code.ts
  src/server/responseTypes/member.ts
  src/server/resquestTypes/member.ts
  src/type/response.types.ts
  src/utils/token.ts
  tsconfig.json
Labels: FEATURE

#31 Mi 54 feature search
  AppInner.tsx
  ios/modutaxi.xcodeproj/project.pbxproj
  src/assets/images/Search/MagnifyingGlassMain.svg
  src/components/LatestSearch.tsx
  src/components/RoomDigest/RoomDigestBox.tsx
  src/components/RoomDigest/SearchLocationButton.tsx
  src/components/SearchBox.tsx
  src/screens/home/Home.tsx
  src/screens/map/MapBottomSheet.tsx
  src/screens/match/CreateMatch.tsx
  src/screens/match/Match.tsx
  src/screens/search/Search.tsx
  src/type/ParamLists.ts
Labels: FEATURE

#33 MI-74 fix folder structure
  src/axios/axios.Instance.ts
  src/axios/guest.axios.instance.ts
  src/axios/guest.axios.method.ts
  src/components/ParticipateUser.tsx
  src/components/WaitUser.tsx
  src/screens/SignIn/SignIn.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/server/api/member.ts
  src/server/errorCodes/member.ts
  src/server/responseTypes/member.ts
  src/server/resquestTypes/member.ts
  src/utils/token.ts
Labels: FIX

#34 MI-75 add token error handler
  src/axios/axios.Instance.ts
  src/screens/signUp/SchoolAuthentication.tsx
  src/server/api/member.ts
  src/server/errorHandler/errorHandler.ts
  src/server/resquestTypes/member.ts
  src/utils/token.ts
Labels: FEATURE

#35 Mi 78 error handler
  App.tsx
  android/app/build.gradle
  android/sentry.properties
  ios/Podfile.lock
  ios/modutaxi.xcodeproj/project.pbxproj
  ios/sentry.properties
  metro.config.js
  package-lock.json
  package.json
  src/axios/axios.Instance.ts
  src/axios/guest.axios.instance.ts
  src/components/Button.tsx
  src/components/Fallback/CustomErrorFallback.tsx
  src/hooks/api/member.ts
  src/hooks/error/error.handler.ts
  src/screens/SignIn/SignIn.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/EmailAuthenticationCode.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/server/api/member.ts
  src/server/errorHandler/errorHandler.ts
  src/server/responseTypes/member.ts
  src/type/custom-library-types/react-native-config.d.ts
  src/utils/sentry.ts
  yarn.lock
Labels: SETTING, FEATURE

#36 MI-77 feature map func
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/images/Map/chevronForward.svg
  src/hooks/map/pinMarker.ts
  src/screens/NaverMap.tsx
  src/screens/map/MainMap.tsx
  src/screens/match/Match.tsx
  yarn.lock
Labels: FEATURE

#39 Mi 102 feature map func
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Marker/RoomMarker.tsx
  src/hooks/map/pinMarker.ts
  src/screens/map/MainMap.tsx
  src/server/api/room.ts
  src/server/responseTypes/map.ts
  src/utils/map.ts
  yarn.lock
Labels: FEATURE
