Repository MODU-TAXI/ios, pull requests merged in 2024-06, with the labels that each got.

#65 Mi 184 pay screen
  AppInner.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/images/Banks/BUSAN.svg
  src/assets/images/Banks/DAEGU.svg
  src/assets/images/Banks/GWANGJU.svg
  src/assets/images/Banks/HANA.svg
  src/assets/images/Banks/IBK.svg
  src/assets/images/Banks/JEJU.svg
  src/assets/images/Banks/JUNBOOK.svg
  src/assets/images/Banks/K.svg
  src/assets/images/Banks/KAKAO.svg
  src/assets/images/Banks/KB.svg
  src/assets/images/Banks/NH.svg
  src/assets/images/Banks/POST.svg
  src/assets/images/Banks/SAEMAUL.svg
  src/assets/images/Banks/SB.svg
  src/assets/images/Banks/SC.svg
  src/assets/images/Banks/SH.svg
  src/assets/images/Banks/SINHAN.svg
  src/assets/images/Banks/SUHYUP.svg
  src/assets/images/Banks/TOSS.svg
  src/assets/images/Banks/URI.svg
  src/assets/images/Calculate/CloseModalButton.svg
  src/assets/images/Calculate/Complete.gif
  src/assets/images/Calculate/CopyButton.svg
  src/assets/images/Calculate/SelectBank.svg
  src/assets/images/Common/Basic_Profile_Gray.svg
  src/assets/images/Common/Basic_Profile_White.svg
  src/assets/images/Common/School_Batch_Main.svg
  src/assets/images/Common/School_Batch_White.svg
  src/components/Button.tsx
  src/components/Calculate/BankModal.tsx
  src/components/Calculate/Banks.tsx
  src/components/Calculate/GetBank.tsx
  src/components/Calculate/InputBox.tsx
  src/components/Calculate/Member.tsx
  src/components/Calculate/Members.tsx
  src/components/Calculate/ParicipateMembers.tsx
  src/components/Calculate/ParticipateMember.tsx
  src/components/Common/Loading.tsx
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/calculate/Account.tsx
  src/screens/calculate/Amount.tsx
  src/screens/calculate/CheckAccount.tsx
  src/screens/calculate/CheckCalculate.tsx
  src/screens/calculate/CompeleteCalculate.tsx
  src/screens/calculate/checkDeparture.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/type/entity/user.ts
  src/type/param/loginStack.ts
  yarn.lock
Labels: FEATURE

#66 Mi 199 declaration
  AppInner.tsx
  package-lock.json
  package.json
  src/assets/images/Declaration/DeclarationAlert.svg
  src/assets/images/Declaration/DeclarationBell.svg
  src/assets/images/Declaration/SelectDropBlack.svg
  src/assets/images/Declaration/SelectDropGray.svg
  src/components/Chat/MessageBox.tsx
  src/components/Chat/Messages.tsx
  src/components/Chat/RoomInfo.tsx
  src/components/Chat/UserModal.tsx
  src/components/Declaration/InputBox.tsx
  src/components/Declaration/SelectBox.tsx
  src/components/RoomDigest/WaitingUser.tsx
  src/components/RoomDigest/WaitingUsers.tsx
  src/hooks/api/report.ts
  src/providers/chatProvider.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/declaration/Declaration.tsx
  src/screens/room/RoomDetail.tsx
  src/server/api/report.ts
  src/server/requestTypes/report.ts
  src/server/responseTypes/report.ts
  src/type/param/loginStack.ts
  yarn.lock
Labels: FEATURE, FIX

#67 Mi 203 fix design
  App.tsx
  src/assets/images/Loading/Loading.gif
  src/components/Calculate/InputBox.tsx
  src/components/Chat/RoomInfo.tsx
  src/components/Common/Loading.tsx
  src/components/Common/TransparentLoading.tsx
  src/components/PhoneNumberInputBox.tsx
  src/hooks/api/chat.ts
  src/hooks/api/rooms.ts
  src/providers/chatProvider.tsx
  src/screens/SignIn/SignIn.tsx
  src/screens/calculate/Account.tsx
  src/screens/calculate/Amount.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/declaration/Declaration.tsx
  src/screens/home/Home.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/EmailAuthenticationCode.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/screens/signUp/RegisterNickname.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/screens/signUp/SurveyFirst.tsx
  src/screens/signUp/SurveySecond.tsx
  src/server/api/chat.ts
  src/utils/text.ts
Labels: FEATURE, FIX

#68 Mi 217 mypage
  src/assets/images/My/Camera.svg
  src/assets/images/My/ContactButton.svg
  src/assets/images/My/LogoutButton.svg
  src/assets/images/My/NextButton.svg
  src/assets/images/My/ResignButton.svg
  src/assets/images/My/SplitLine.svg
  src/hooks/api/member.ts
  src/providers/chatProvider.tsx
  src/screens/calculate/Account.tsx
  src/screens/calculate/Amount.tsx
  src/screens/my/MyPage.tsx
  src/server/api/member.ts
  src/server/requestTypes/member.ts
  src/server/responseTypes/member.ts
Labels: FEATURE

#75 Mi 192 feature room filtering
  package-lock.json
  src/assets/images/Map/xmark.svg
  src/components/Map/MapBottomSheet.tsx
  src/components/Map/SpotFilterModal.tsx
  src/components/RoomDigest/SpotFilterButton.tsx
  src/components/Search/RecommendedSearch.tsx
  src/components/Search/SpotSelectionSearch.tsx
  src/hooks/api/rooms.ts
  src/hooks/api/spot.ts
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/map/ArrivalMap.tsx
  src/screens/map/MainMap.tsx
  src/screens/search/Search.tsx
  src/server/api/room.ts
  src/server/requestTypes/room.ts
  src/server/responseTypes/room.ts
  src/server/responseTypes/spot.ts
  src/type/entity/room.ts
  src/type/entity/spot.ts
Labels: FEATURE, REFACTOR

#77 Mi 265 fix design
  ios/Podfile.lock
  ios/modutaxi/LaunchScreen.storyboard
  package-lock.json
  package.json
  src/axios/axios.Instance.ts
  src/components/Chat/MessageBox.tsx
  src/components/Chat/RoomInfo.tsx
  src/components/Home/MyParty.tsx
  src/components/Home/Party.tsx
  src/components/RoomDigest/SelectedRoomDigest.tsx
  src/components/RoomDigest/ZeroUser.tsx
  src/hooks/api/rooms.ts
  src/screens/chat/ChatRoom.tsx
  src/screens/home/Home.tsx
  src/screens/room/RoomDetail.tsx
  src/server/responseTypes/s3.ts
  src/utils/effect.ts
  src/utils/image.ts
  yarn.lock
Labels: FIX, REFACTOR

#78 Mi 241 refactor search params
  package-lock.json
  src/components/DatePicker.tsx
  src/components/Home/Party.tsx
  src/components/RoomDigest/RoomDigestBox.tsx
  src/components/RoomDigest/RoomMap.tsx
  src/components/RoomDigest/SelectedRoomDigest.tsx
  src/hooks/api/rooms.ts
  src/hooks/api/search.ts
  src/screens/map/ArrivalMap.tsx
  src/screens/map/DepartureMap.tsx
  src/screens/map/MainMap.tsx
  src/screens/search/DepartureSearch.tsx
  src/server/responseTypes/room.ts
  src/type/entity/room.ts
  src/type/param/loginStack.ts
Labels: REFACTOR

#79 Mi 279 History Screen
  .eslintrc
  AppInner.tsx
  package-lock.json
  src/assets/images/History/AfterBar.svg
  src/assets/images/History/Arrow.svg
  src/assets/images/History/BeforeBar.svg
  src/assets/images/History/DropDown.svg
  src/assets/images/History/NextButton.svg
  src/components/Chat/MessageInputBox.tsx
  src/components/Common/UserModal.tsx
  src/components/History/HistoryInfo.tsx
  src/components/History/HistoryMember.tsx
  src/components/History/HistoryMembers.tsx
  src/hooks/api/history.ts
  src/screens/chat/ChatRoom.tsx
  src/screens/history/History.tsx
  src/screens/history/HistoryDetail.tsx
  src/screens/my/MyPage.tsx
  src/screens/room/RoomDetail.tsx
  src/server/api/history.ts
  src/server/responseTypes/history.ts
  src/type/entity/history.ts
  src/type/param/loginStack.ts
Labels: FEATURE, REFACTOR

#80 Mi 270 mypage
  AppInner.tsx
  src/assets/images/Common/Complete.gif
  src/components/My/Account.tsx
  src/components/My/Accounts.tsx
  src/components/My/InquiryInputBox.tsx
  src/components/My/InquirySelectBox.tsx
  src/components/Timer.tsx
  src/screens/SignIn/SignIn.tsx
  src/screens/calculate/CompeleteCalculate.tsx
  src/screens/declaration/Declaration.tsx
  src/screens/history/History.tsx
  src/screens/my/Inquiry.tsx
  src/screens/my/ManageAccount.tsx
  src/screens/my/ManageAlarm.tsx
  src/screens/my/MyPage.tsx
  src/screens/my/PatchAccount.tsx
  src/screens/my/PatchSchoolEmailAuthentication.tsx
  src/screens/my/PatchUserInfo.tsx
  src/screens/my/PatchUserInfoAuthentication.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/withdraw/WithdrawCheck.tsx
  src/screens/withdraw/WithdrawComplete.tsx
  src/screens/withdraw/WithdrawLast.tsx
  src/screens/withdraw/WithdrawSurvey.tsx
  src/type/param/loginStack.ts
Labels: FEATURE, FIX, REFACTOR

#81 Mi 293 exit api
  src/assets/images/Header/HeaderDots.svg
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ExitModal.tsx
  src/components/RoomDigest/RoomHeader.tsx
  src/components/RoomDigest/UpdateModal.tsx
  src/hooks/api/rooms.ts
  src/screens/chat/ChatRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/server/api/room.ts
  src/server/requestTypes/room.ts
  src/server/responseTypes/room.ts
Labels: FEATURE

#82 Mi 259 feature tag filtering
  src/assets/images/RadioBox/SelectedRadioButtonGray.svg
  src/components/Map/DropDownModal.tsx
  src/components/Map/MapBottomSheet.tsx
  src/components/RoomDigest/FilterButton.tsx
  src/screens/map/MainMap.tsx
  src/server/requestTypes/room.ts
  src/type/entity/room.ts
Labels: FEATURE, FIX

#83 Mi 286 refactor design
  App.tsx
  src/assets/images/Toast/Card.svg
  src/assets/images/Toast/Chat.svg
  src/assets/images/Toast/Check.svg
  src/assets/images/Toast/CompleteMatchText.svg
  src/assets/images/Toast/RegisterAdvanceText.svg
  src/components/Header.tsx
  src/components/Home/Etc.tsx
  src/components/ProgressBar.tsx
  src/components/RoomDigest/UpdateModal.tsx
  src/components/SelectBox.tsx
  src/config/toastConfig.tsx
  src/hooks/api/rooms.ts
  src/screens/chat/ChatRoom.tsx
  src/screens/my/PatchNickname.tsx
  src/screens/my/PatchUserInfoAuthentication.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/CheckPermission.tsx
  src/screens/signUp/CompleteSignUp.tsx
  src/screens/signUp/EmailAuthenticationCode.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/screens/signUp/RegisterNickname.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/screens/signUp/SurveyFirst.tsx
  src/screens/signUp/SurveySecond.tsx
  src/utils/toastMessage.ts
Labels: FEATURE, FIX, REFACTOR

#84 Mi 13 feature apple login
  ios/Podfile.lock
  ios/modutaxi/modutaxi.entitlements
  package-lock.json
  package.json
  src/assets/images/SignIn/ModutaxiLogo.svg
  src/hooks/api/member.ts
  src/screens/SignIn/SignIn.tsx
  src/server/api/member.ts
  src/server/requestTypes/member.ts
  src/server/responseTypes/member.ts
  yarn.lock
Labels: FEATURE, REFACTOR

#85 MI-289 apply splash screen
  ios/Podfile.lock
  ios/modutaxi.xcodeproj/project.pbxproj
  ios/modutaxi/AppDelegate.mm
  ios/modutaxi/Images.xcassets/Contents.json
  ios/modutaxi/Images.xcassets/LaunchScreen.imageset/Contents.json
  ios/modutaxi/Images.xcassets/LaunchScreen.imageset/LaunchImage.png
  ios/modutaxi/Images.xcassets/LaunchScreen.imageset/LaunchImage~iphone-320x480.png
  ios/modutaxi/Images.xcassets/LaunchScreen.imageset/LaunchImage~iphone_640x960.png
  ios/modutaxi/LaunchScreen.storyboard
  package-lock.json
  package.json
  src/hooks/login.ts
  yarn.lock
Labels: FEATURE

#88 Mi 323 rest api
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/images/Alarm/Caculate_Complete.svg
  src/assets/images/Alarm/Declaration.svg
  src/assets/images/Alarm/Event.svg
  src/assets/images/Alarm/Match.svg
  src/assets/images/My/InquiryKakao.svg
  src/assets/images/My/InquiryMail.svg
  src/components/Alarm/alarm.tsx
  src/components/Alarm/alarms.tsx
  src/components/My/InquiryInputBox.tsx
  src/components/My/InquirySelectBox.tsx
  src/hooks/api/alarms.ts
  src/hooks/api/history.ts
  src/hooks/api/member.ts
  src/screens/alarm/alarm.tsx
  src/screens/history/History.tsx
  src/screens/my/Inquiry.tsx
  src/screens/withdraw/WithdrawCheck.tsx
  src/screens/withdraw/WithdrawComplete.tsx
  src/screens/withdraw/WithdrawLast.tsx
  src/server/api/alarms.ts
  src/server/api/history.ts
  src/server/api/member.ts
  src/server/responseTypes/alarm.ts
  src/server/responseTypes/history.ts
  src/type/entity/alarm.ts
  yarn.lock
Labels: FEATURE

#89 Mi 329 error handler
  src/assets/images/Common/Reload.svg
  src/assets/images/Toast/Error.svg
  src/axios/axios.Instance.ts
  src/components/Fallback/ChatErrorBoundary.tsx
  src/components/Fallback/CustomErrorFallback.tsx
  src/components/Fallback/RoomErrorBoundary.tsx
  src/components/Home/MyParty.tsx
  src/components/Home/UserSummary.tsx
  src/config/toastConfig.tsx
  src/hooks/api/account.ts
  src/hooks/api/member.mail.ts
  src/hooks/api/member.sms.ts
  src/hooks/api/member.ts
  src/hooks/api/onboarding.ts
  src/hooks/api/payment.ts
  src/hooks/api/report.ts
  src/hooks/api/rooms.ts
  src/hooks/api/spot.ts
  src/hooks/fcm.ts
  src/screens/chat/ChatRoom.tsx
  src/screens/history/History.tsx
  src/screens/home/Home.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/server/errorHandler/member.mail.ts
  src/server/errorHandler/member.sms.ts
  src/server/errorHandler/member.ts
  src/server/errorHandler/mutateErrorHandler.ts
  src/server/errorHandler/onBoarding.ts
  src/server/errorHandler/suspenseErrorHandler.tsx
  src/utils/toastMessage.ts
Labels: FEATURE, FIX

#90 Mi 303 refactor
  App.tsx
  deepLinkConfig.ts
  src/assets/images/Chat/CompleteStatus.svg
  src/assets/images/Chat/DeleteStatus.svg
  src/assets/images/Chat/Dot.svg
  src/assets/images/Chat/ProceedingStatus.svg
  src/assets/images/Home/Bell.svg
  src/components/Chat/JoinMessageBox.tsx
  src/components/Chat/LeaveMessageBox.tsx
  src/components/Chat/MessageBox.tsx
  src/components/Chat/RoomInfo.tsx
  src/components/Home/HomeHeader.tsx
  src/components/InputBox.tsx
  src/components/Timer.tsx
  src/hooks/api/alarms.ts
  src/hooks/api/chat.ts
  src/hooks/api/member.sms.ts
  src/screens/chat/ChatRoom.tsx
  src/screens/history/HistoryDetail.tsx
  src/screens/home/Home.tsx
  src/screens/my/MyPage.tsx
  src/screens/my/PatchUserInfo.tsx
  src/screens/my/PatchUserInfoAuthentication.tsx
  src/screens/room/RoomDetail.tsx
  src/server/api/alarms.ts
  src/server/api/member.sms.ts
  src/server/requestTypes/member.sms.ts
  src/server/responseTypes/alarm.ts
  src/server/responseTypes/member.sms.ts
  src/server/responseTypes/room.ts
  src/type/entity/room.ts
  src/type/param/loginStack.ts
  src/utils/fcm.ts
  src/utils/notifee.ts
Labels: FEATURE, FIX, REFACTOR
