Repository MODU-TAXI/ios, pull requests merged in 2024-05, with the labels that each got.

#40 Mi 111 feat match api
  src/components/RoomDigest/RoomTag.tsx
  src/screens/map/MainMap.tsx
  src/screens/match/Match.tsx
  src/server/api/room.ts
  src/server/responseTypes/map.ts
  src/server/responseTypes/room.ts
  src/utils/map.ts
  src/utils/room.ts
Labels: FEATURE

#43 Mi 111 feat match api
  src/hooks/api/rooms.ts
  src/hooks/api/spot.ts
  src/screens/match/Match.tsx
  src/server/api/spot.ts
  src/server/requestTypes/spot.ts
  src/server/responseTypes/spot.ts
Labels: FEATURE

#45 Mi 114 feature main map
  package-lock.json
  package.json
  src/assets/images/RadioBox/RadioButtonBox.svg
  src/assets/images/RoomDigest/ChevronDownBox.svg
  src/assets/images/RoomDigest/DottedLine.svg
  src/assets/images/RoomDigest/SpotCircleMint.svg
  src/assets/images/RoomDigest/SpotGray.svg
  src/assets/images/RoomDigest/SpotPinGray.svg
  src/assets/images/RoomDigest/SpotPinMint.svg
  src/components/RoomDigest/FilterButton.tsx
  src/components/RoomDigest/RoomCategories.tsx
  src/components/RoomDigest/RoomCategory.tsx
  src/components/RoomDigest/RoomDigestBox.tsx
  src/components/RoomDigest/SearchLocationButton.tsx
  src/components/RoomDigest/SpotFilterButton.tsx
  src/hooks/api/rooms.ts
  src/screens/map/MainMap.tsx
  src/screens/map/MapBottomSheet.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/test.tsx
  src/server/api/room.ts
  src/server/responseTypes/room.ts
  src/type/entity/room.ts
  src/utils/map.ts
  src/utils/room.ts
  tailwind.config.js
  yarn.lock
Labels: FEATURE

#48 FIx tailwind version error
  App.tsx
  AppInner.tsx
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/DatePicker.tsx
  src/components/RoomDigest/RoomDigestBox.tsx
  src/screens/SignIn/SignIn.tsx
  src/screens/signUp/CheckPermission.tsx
  tsconfig.json
  yarn.lock
Labels: FIX

#49 MI-135 add param type
  .eslintrc
  AppInner.tsx
  babel.config.js
  src/components/Button.tsx
  src/components/Chat/Messages.tsx
  src/components/RoomDigest/ParticipateUser.tsx
  src/components/RoomDigest/ParticipateUsers.tsx
  src/components/RoomDigest/RoomCategories.tsx
  src/components/RoomDigest/RoomCategory.tsx
  src/components/RoomDigest/RoomMap.tsx
  src/components/RoomDigest/WaitingUser.tsx
  src/components/RoomDigest/WaitingUsers.tsx
  src/hooks/api/member.ts
  src/hooks/api/rooms.ts
  src/hooks/navigation.ts
  src/screens/SignIn/SignIn.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/home/Home.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/search/Search.tsx
  src/screens/signUp/Authentication.tsx
  src/screens/signUp/CheckPermission.tsx
  src/screens/signUp/CompleteSignUp.tsx
  src/screens/signUp/EmailAuthenticationCode.tsx
  src/screens/signUp/PhoneAuthenticationCode.tsx
  src/screens/signUp/SchoolAuthentication.tsx
  src/screens/signUp/SurveyFirst.tsx
  src/screens/signUp/SurveySecond.tsx
  src/type/custom-library-types/declarations.d.ts
  src/type/custom-library-types/react-native-config.d.ts
  src/type/custom-library-types/stomp.d.ts
  src/type/entity/room.ts
  src/type/param/loginStack.ts
  src/type/param/rootStack.ts
  src/types/ParamLists.ts
  tsconfig.json
Labels: FEATURE

#51 Mi 141 feature connect room detail
  AppInner.tsx
  ios/modutaxi.xcodeproj/project.pbxproj
  src/assets/images/Map/currentLocation.svg
  src/assets/images/Map/plusCircleFill.svg
  src/assets/images/Map/refreshButton.svg
  src/components/CreateRoomButton.tsx
  src/components/RoomDigest/RoomMap.tsx
  src/screens/map/MainMap.tsx
Labels: FEATURE

#52 Mi 139 fcm
  AppInner.tsx
  ios/Podfile.lock
  ios/modutaxi.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/axios/axios.Instance.ts
  src/hooks/api/member.ts
  src/hooks/fcm.ts
  src/hooks/login.ts
  src/screens/home/Home.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/test.tsx
  src/server/api/room.ts
  src/type/message/fcm.ts
  src/utils/fcm.ts
  yarn.lock
Labels: FEATURE

#53 Mi 145 chat room
  src/assets/images/Chat/Arrow.svg
  src/assets/images/Chat/Camera.svg
  src/assets/images/Chat/Declaration.svg
  src/assets/images/Chat/Dot.svg
  src/assets/images/Chat/Money.svg
  src/assets/images/Chat/People.svg
  src/assets/images/Chat/ProfileImage.svg
  src/assets/images/Chat/Question.svg
  src/assets/images/Chat/SchoolBadge.svg
  src/assets/images/Chat/SendButton.svg
  src/assets/images/Chat/UserImage.svg
  src/components/Chat/MessageBox.tsx
  src/components/Chat/MessageInputBox.tsx
  src/components/Chat/Messages.tsx
  src/components/Chat/RoomInfo.tsx
  src/components/Chat/UserModal.tsx
  src/components/Header.tsx
  src/providers/chatProvider.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/server/responseTypes/chat.ts
  src/type/entity/chat.ts
  src/type/param/loginStack.ts
Labels: FEATURE

#55 Mi 149 homepage
  AppInner.tsx
  package-lock.json
  package.json
  src/assets/images/BottomTab/ClickedHome.svg
  src/assets/images/BottomTab/ClickedMap.svg
  src/assets/images/BottomTab/ClickedProfile.svg
  src/assets/images/BottomTab/ClickedTaxi.svg
  src/assets/images/BottomTab/UnCilckedMap.svg
  src/assets/images/BottomTab/UnClickedHome.svg
  src/assets/images/BottomTab/UnClickedProfile.svg
  src/assets/images/BottomTab/UnClickedTaxi.svg
  src/assets/images/Chat/ProfileImage.svg
  src/assets/images/Home/Bell.svg
  src/assets/images/Home/Check.svg
  src/assets/images/Home/Logo.svg
  src/assets/images/Home/Map.svg
  src/assets/images/Home/Popper.svg
  src/assets/images/Home/Receipt.svg
  src/assets/images/Home/Road.svg
  src/assets/images/Home/Search.svg
  src/assets/images/Home/Taxi.svg
  src/components/BottomTab/HomeTab.tsx
  src/components/BottomTab/MapTab.tsx
  src/components/BottomTab/MyPageTab.tsx
  src/components/Chat/MessageBox.tsx
  src/components/Home/Etc.tsx
  src/components/Home/InputBox.tsx
  src/components/Home/Middle.tsx
  src/components/Home/Parties.tsx
  src/components/Home/Party.tsx
  src/components/Home/Top.tsx
  src/screens/home/Home.tsx
  src/screens/my/MyPage.tsx
  src/type/param/loginStack.ts
  yarn.lock
Labels: FEATURE

#57 Mi 157 refactor
  App.tsx
  AppInner.tsx
  deepLinkConfig.ts
  index.js
  ios/Podfile.lock
  ios/modutaxi/AppDelegate.mm
  package-lock.json
  package.json
  src/assets/images/Loading/LoadingCircle.gif
  src/assets/images/Loading/LoadingCircle.svg
  src/axios/axios.Instance.ts
  src/components/Common/Loading.tsx
  src/components/Home/Top.tsx
  src/hooks/login.ts
  src/hooks/notifee.ts
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/SignIn/SignIn.tsx
  src/screens/home/Home.tsx
  src/screens/main/Main.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/server/api/member.ts
  src/server/responseTypes/member.ts
  src/utils/fcm.ts
  src/utils/notifee.ts
  yarn.lock
Labels: FEATURE, FIX, REFACTOR

#58 MI-158 fix rooms api,fetching
  src/hooks/api/rooms.ts
  src/server/api/room.ts
  src/server/responseTypes/room.ts
  src/type/entity/room.ts
Labels: FIX

#59 Mi 163 chat image
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/Chat/MessageBox.tsx
  src/components/Chat/MessageInputBox.tsx
  src/components/Chat/Messages.tsx
  src/components/Common/Loading.tsx
  src/components/Header.tsx
  src/components/RoomDigest/ParticipateUser.tsx
  src/hooks/api/rooms.ts
  src/providers/chatProvider.tsx
  src/screens/chat/ChatRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/server/responseTypes/room.ts
  src/server/responseTypes/s3.ts
  src/type/entity/room.ts
  src/utils/image.ts
  yarn.lock
Labels: FEATURE

#60 MI-168 refactor home ui
  App.tsx
  AppInner.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/images/Home/Bell.svg
  src/assets/images/Home/Logo.svg
  src/assets/images/Home/Map.svg
  src/assets/images/Home/SadFace.svg
  src/assets/images/Home/Search.svg
  src/assets/images/Home/Taxi.svg
  src/components/Chat/MessageBox.tsx
  src/components/Chat/RoomInfo.tsx
  src/components/Home/Etc.tsx
  src/components/Home/InputBox.tsx
  src/components/Home/Middle.tsx
  src/components/Home/MyParty.tsx
  src/components/Home/NoParty.tsx
  src/components/Home/Parties.tsx
  src/components/Home/Party.tsx
  src/components/Home/Top.tsx
  src/hooks/api/rooms.ts
  src/screens/chat/ChatRoom.tsx
  src/screens/home/Home.tsx
  src/screens/room/RoomDetail.tsx
  src/server/api/room.ts
  src/server/responseTypes/room.ts
  src/type/entity/room.ts
  src/type/entity/user.ts
  src/type/param/loginStack.ts
  src/utils/fcm.ts
  src/utils/notifee.ts
  yarn.lock
Labels: FEATURE, FIX

#63 MI-185 alarm screen ui
  AppInner.tsx
  src/assets/images/Alarm/Caculate_Complete.svg
  src/assets/images/Alarm/Calculate.svg
  src/assets/images/Alarm/Declaration_Complete.svg
  src/assets/images/Alarm/Event.svg
  src/assets/images/Alarm/Match_Complete.svg
  src/components/Alarm/alarm.tsx
  src/components/Alarm/alarms.tsx
  src/components/Home/Top.tsx
  src/screens/alarm/alarm.tsx
  src/screens/home/Home.tsx
  src/type/entity/alarm.ts
  src/type/param/loginStack.ts
Labels: FEATURE

#64 Mi 119 feat create room
  AppInner.tsx
  package-lock.json
  src/assets/images/Map/MapPin.svg
  src/assets/images/Map/MapPinGray.svg
  src/assets/images/Map/chevronBackwardCircle.svg
  src/assets/images/Map/refreshButton.svg
  src/assets/images/Match/DottedLine.svg
  src/assets/images/Search/SpotCircleMintReverse.svg
  src/components/CreateRoomButton.tsx
  src/components/DatePicker.tsx
  src/components/Description.tsx
  src/components/Home/Party.tsx
  src/components/RoomDigest/ParticipateUser.tsx
  src/components/RoomDigest/ParticipateUsers.tsx
  src/components/RoomDigest/WaitingUser.tsx
  src/components/RoomDigest/WaitingUsers.tsx
  src/components/Search/LatestSearch.tsx
  src/components/Search/RecommendedSearch.tsx
  src/components/Search/SearchBox.tsx
  src/components/Search/SpotSearch.tsx
  src/components/Search/TransparentSearchBox.tsx
  src/hooks/api/rooms.ts
  src/hooks/api/search.ts
  src/hooks/api/spot.ts
  src/hooks/permission/checkLocation.ts
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/map/MainMap.tsx
  src/screens/map/departureMap.tsx
  src/screens/room/CreateRoom.tsx
  src/screens/room/PatchRoom.tsx
  src/screens/room/RoomDetail.tsx
  src/screens/search/Search.tsx
  src/server/api/spot.ts
  src/server/requestTypes/spot.ts
  src/server/responseTypes/spot.ts
  src/type/custom-library-types/react-native-config.d.ts
  src/type/entity/search.ts
  src/type/entity/spot.ts
  src/type/param/loginStack.ts
  src/utils/map.ts
  src/utils/search.ts
Labels: FEATURE
